[workspace]
members = [
    "lesson-01",
    "lesson-02",
    "lesson-03",
    "lesson-04",
    "lesson-05",
    "lesson-06",
    "lesson-07",
    "lesson-08",
    "lesson-09",
    "lesson-10",
    "lesson-11",
    "lesson-12",
]