[package]
name = "lesson-03-triangle"
version = "0.1.0"
authors = ["Nerijus Arlauskas <nercury@gmail.com>"]

[dependencies]
gl = "0.10.0"

[dependencies.sdl2]
version = "0.31.0"
features = ["bundled", "static-link"]